### ISSUE TITLE
Some errors... running node v10.16.1

### ISSUE THREAD

**Issue by GaryMatthews** [MLP-VectorClub/PennyCurve#4]
Just having a play with discord and possible use of bots. after a bit of a struggle i managed to get it online. unfortunately seam to be having issues.    ....  i accidently dropped this in the Muffins repo and prolly without enough information... 

```
[2019-12-02 19:12:15.446] [INFO]   ~ Ready ~
[2019-12-02 19:12:47.761] [LOG]    XXX#XXXX ran !help from #general (M#XXXXXXXXXXXXX)
[2019-12-02 19:12:47.790] [LOG]    null
[2019-12-02 19:12:47.791] [ERROR]  (node:29668) DeprecationWarning: Collection#exists: use Collection#some instead
[2019-12-02 19:12:47.792] [ERROR]  (node:29668) DeprecationWarning: Collection#find: pass a function instead
[2019-12-02 19:12:47.792] [ERROR]  TypeError: Cannot read property 'constructor' of null
    at Server.mention (xxxxxxxxx/classes/Server.js:689:58)
    at Object.<anonymous> (xxxxxxxxx/commands/casual.js:9:68)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at fs.readdirSync.forEach.file (xxxxxxxxx/commands/help.js:55:14)
```

**Comment by GaryMatthews** [comment]
sorry about the bad first post for some reason it took newline as an intent to post when really i wanted a new line.

**Comment by SeinopSys** [comment]
Technically these are just deprecation warnings, the code should still function nonetheless. I will try to update the code to remove these but you should be able to run the both regardless. The server this is running on is using the latest v12.x of node currently, I can't guarantee it will work with anything else. The issue in your case seems to stem from this line:

https://github.com/MLP-VectorClub/PennyCurve/blob/615e58b05d7168d6d022680e21dfbb123eb259bb/commands/casual.js#L9

This code tries to mention the `#casual` channel but since it likely does not exist on your server it's returning `null` which in turn causes the code that mentions things to throw because it's expecting an object. The bot isn't exactly meant for general use, it's built for a specific comunnity and the relevant channels from said are hard coded.

**Comment by SeinopSys** [comment]
I've updated the code with some things that should help with identifying this issue in the future, be sure to pull the lateste changes. I've also made the command help text a function so the bot doesn't crash like this by just fetching the command object, the help text actually has to be requested for this issue to reappear. Hopefully the changes will help you.
